name: export-and-branch-solution

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution from Power Platform'
        required: true
        default: ALMLab
      solution_exported_folder:
        description: 'Folder for exported solution'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Folder for unpacked solution'
        required: true
        default: out/solutions/
      solution_target_folder:
        description: 'Target folder for git check-in'
        required: true
        default: solutions/

env:
  ENVIRONMENT_URL: https://org8777e192.crm8.dynamics.com/

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Who Am I - Service Principal Auth
        uses: microsoft/powerplatform-actions/who-am-i@v0
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ secrets.PowerPlatformClientID }}
          client-secret: ${{ secrets.PowerPlatformClientSecret }}
          tenant-id: ${{ secrets.PowerPlatformTenantID }}

      - name: Export Solution from DEV
        uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ secrets.PowerPlatformClientID }}
          client-secret: ${{ secrets.PowerPlatformClientSecret }}
          tenant-id: ${{ secrets.PowerPlatformTenantID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: ${{ github.event.inputs.solution_exported_folder }}${{ github.event.inputs.solution_name }}.zip

      - name: Unpack Solution
        uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ github.event.inputs.solution_exported_folder }}${{ github.event.inputs.solution_name }}.zip
          solution-folder: ${{ github.event.inputs.solution_folder }}${{ github.event.inputs.solution_name }}
          solution-type: 'Unmanaged'
          overwrite-files: true

      - name: Branch Solution for Pull Request
        uses: microsoft/powerplatform-actions/branch-solution@v0
        with:
          solution-folder: ${{ github.event.inputs.solution_folder }}${{ github.event.inputs.solution_name }}
          solution-target-folder: ${{ github.event.inputs.solution_target_folder }}${{ github.event.inputs.solution_name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
